<a href="https://colab.research.google.com/github/1sazzad/PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Tensors**


*   A torch. Tensor is a multi-dimensional matrix containing elements of a single data type
*   Similar to Numpy array, but full of fun things that make them work better on GPU's(vs regular CPU's)
*   default data type of float32.
*   More suitable for deep learning than a numpy array



In [4]:
import torch
import numpy as np

#**List**


In [2]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

#**Numpy Array**

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.95468251, 0.54585634, 0.19194879, 0.021211  ],
       [0.85095469, 0.16683553, 0.02064169, 0.77472611],
       [0.60933361, 0.99537233, 0.4578214 , 0.18046337]])

In [8]:
np1.dtype

dtype('float64')

#**Tensors**

In [10]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype


torch.float32

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9547, 0.5459, 0.1919, 0.0212],
        [0.8510, 0.1668, 0.0206, 0.7747],
        [0.6093, 0.9954, 0.4578, 0.1805]], dtype=torch.float64)