<a href="https://colab.research.google.com/github/1sazzad/PyTorch/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import torch
import numpy as np

tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [25]:
# Addition Shorthand
tensor_a + tensor_b


tensor([ 6,  8, 10, 12])

In [26]:
# Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [27]:
# Subtraction shorthand
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [28]:
# Sub function
torch.subtract(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [29]:
# multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [30]:
# multiplication Longhand
torch.multiply(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [31]:
# Division
tensor_b / tensor_a


tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [32]:
# Div Longhand
torch.div(tensor_b,tensor_a)
#torch.divide(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [33]:
# Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [34]:
# Reminder Longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [35]:
# Exponent / Power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [36]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [37]:
# Reassignment
tensor_a += tensor_b
tensor_a

tensor([ 6,  8, 10, 12])